### ISSUE TITLE
Go over TODO's and FIXME's

### ISSUE THREAD

**Issue by Infinisil** [tweag/webauthn#81]

**Comment by ErinvanderVeen** [comment]
### src/Crypto/WebAuthn/Model.hs
- [ ] 700:    -- FIXME: We don't allow encoding it as null here, because it doesn't seem

### src/Crypto/WebAuthn/Metadata/Service/Processing.hs
- [ ] 80:        -- FIXME: Return a better error here, but we can't modify the jose libraries error type
- [ ] 102:        -- FIXME: We're currently discarding these errors by necessity, because we're bound by the JOSE libraries error type

### src/Crypto/WebAuthn/Metadata/Statement/IDL.hs
- [ ] 77:    -- FIXME: The spec declares this as an unsigned long, but the blob they
- [ ] 182:    -- FIXME: The spec wrongfully declares the values to be DOMString's when they really aren't in the provided blob

### server/src/Main.hs
- [ ] 220:  -- FIXME: Update signature count in database
- [ ] 282:  -- FIXME

### tests/MetadataSpec.hs
- [ ] 23:  -- TODO: Property tests: Generate random metadata, encode and sign it, decode and verify it, make sure it's the same result

### tests/PublicKeySpec.hs
- [ ] 139:  -- TODO: Find out how encoding changed

### tests/Emulation/Authenticator.hs
- [ ] 213:      -- TODO: Use deterministic random number generator, and ensure that we
- [ ] 378:      -- TODO: We don't suport extensions
- [ ] 450:-- TODO: Surely there must be a beter function than lookpMin . filter

### src/Crypto/WebAuthn/Model.hs
- [ ] 473:-- TODO: 'RpId' is used for both https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrpentity-id
- [ ] 642:-- TODO: Implement a way to specify extensions, or implement them here directly
- [ ] 654:-- TODO: Implement a way to specify extensions, or implement them here directly
- [ ] 930:    -- TODO: Implement this
- [ ] 1228:      -- TODO: This property is currently not propagated by webauthn-json

### src/Crypto/WebAuthn/Metadata/Statement/IDL.hs
- [ ] 174:-- TODO: Replace Text with https://hackage.haskell.org/package/aeson-2.0.2.0/docs/Data-Aeson-Key.html#t:Key when updating aeson
- [ ] 181:  = -- TODO: Replace Text with https://hackage.haskell.org/package/aeson-2.0.2.0/docs/Data-Aeson-Key.html#t:Key when updating aeson

### src/Crypto/WebAuthn/Operations/Assertion.hs
- [ ] 99:  -- TODO
- [ ] 117:  -- TODO: Implement extensions
- [ ] 194:  -- TODO
- [ ] 218:    -- TODO: Maybe throw warning that user verification was preferred but not provided
- [ ] 220:    -- TODO: Maybe throw warning that user verification was discouraged but provided
- [ ] 232:  -- TODO

### src/Crypto/WebAuthn/Operations/Attestation.hs
- [ ] 71:  | -- | TODO: Fix this description
- [ ] 281:    -- TODO: Implement extensions
- [ ] 309:    -- TODO: Token binding is not currently supported.
- [ ] 344:      -- TODO: Maybe throw warning that user verification was preferred but not provided
- [ ] 346:      -- TODO: Maybe throw warning that user verification was discouraged but provided
- [ ] 366:    -- TODO: Extensions aren't currently implemented

### src/Crypto/WebAuthn/Metadata/Service/Processing.hs
- [ ] 76:    -- TODO: Implement step 4 of the spec, which says to try to get the chain from x5u first before trying x5c
- [ ] 86:    -- TODO: Check CRLs, see https://github.com/tweag/haskell-fido2/issues/23

### src/Crypto/WebAuthn/Metadata/Statement/Decode.hs
- [ ] 56:  -- TODO: Remove Text.strip, it's only needed because of a spec violation, see https://github.com/tweag/haskell-fido2/issues/68
- [ ] 57:  -- TODO: Don't use decodeLenient, it's only needed because of a spec violation, see TODO
- [ ] 138:        -- TODO: Use non-lenient decoding, it's only needed because of a spec violation,

### src/Crypto/WebAuthn/Metadata/Service/Types.hs
- [ ] 63:    -- TODO: Implement this, currently not used in the blob however
- [ ] 70:    -- rogueListURL, rogueListHash. TODO, but not currently used in the

### src/Crypto/WebAuthn/WebIDL.hs
- [ ] 31:-- TODO: This implementation doesn't allow invalid UTF-16 codepoints, which
- [ ] 41:-- TODO: This implementation allows for surrogate code points. Figure out if

### src/Crypto/WebAuthn/Operations/Attestation/AndroidKey.hs
- [ ] 272:    -- TODO: Allow the users of the library set the required trust level

### src/Crypto/WebAuthn/Model/Binary/Decoding.hs
- [ ] 203:      -- TODO
- [ ] 251:    -- TODO

### src/Crypto/WebAuthn/Operations/Attestation/TPM.hs
- [ ] 580:      -- TODO: Left out for now, until proven needed

### src/Crypto/WebAuthn/Operations/Attestation/FidoU2F.hs
- [ ] 119:        -- TODO: Will we only get named curves?
- [ ] 160:        -- TODO: Pass along SignatureFailure to error

### src/Crypto/WebAuthn/Model/JavaScript/Decoding.hs
- [ ] 65:  -- TODO: Implement extension support

### src/Crypto/WebAuthn/UAF.hs
- [ ] 23:-- TODO: Implement a way to reproduce this value

### src/Crypto/WebAuthn/PublicKey.hs
- [ ] 137:-- TODO: We could do without this type by going from Cryptonite's NamedCurve
- [ ] 163:          -- TODO: left?
- [ ] 186:        -- TODO(arianvp): Implement compressed curve. Waiting for

### src/Crypto/WebAuthn/Model/JavaScript/Encoding.hs
- [ ] 60:  -- TODO: Implement extension support
- [ ] 183:        -- TODO: Extensions aren't currently supported
- [ ] 205:        -- TODO: Extensions are not currently supported

### server/src/PendingOps.hs
- [ ] 220:      -- TODO: Do something less invasive than printing the removed options
